"""Terms of Service page."""

import streamlit as st


def render():
    """Render the Terms of Service page."""
    st.markdown("## Terms of Service")
    st.caption("Last updated: May 2026")
    st.divider()

    st.markdown("""
### 1. Acceptance of Terms

By creating an account or using Replydesk AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.

---

### 2. Description of Service

Replydesk AI is an AI-powered productivity tool that helps professionals generate client replies, emails, task summaries, daily reports, and other professional communication content using OpenAI's language models.

---

### 3. Account Registration

- You must provide a valid email address and verify it to activate your account.
- You are responsible for maintaining the confidentiality of your password.
- You must notify us immediately of any unauthorized use of your account.
- You must be at least 13 years old to use the Service.

---

### 4. Acceptable Use

You agree not to use the Service to:

- Generate spam, phishing emails, or deceptive content
- Harass, threaten, or harm any individual or group
- Violate any applicable laws or regulations
- Attempt to reverse-engineer, scrape, or abuse the Service
- Share your account credentials with others

We reserve the right to suspend or terminate accounts that violate these terms.

---

### 5. AI-Generated Content

- Content generated by the Service is produced by AI and may not always be accurate, appropriate, or complete.
- You are solely responsible for reviewing, editing, and using any generated content.
- We do not claim ownership of content you generate using the Service.
- You retain full ownership of your input and output content.

---

### 6. Rate Limits and Fair Use

- Free accounts are subject to a daily generation limit (currently 50 generations per day).
- Limits may change with reasonable notice.
- Attempting to circumvent rate limits may result in account suspension.

---

### 7. Privacy

Your use of the Service is also governed by our [Privacy Policy](/). We collect and process personal data as described therein.

---

### 8. Third-Party Services

The Service uses OpenAI's API to generate content. Your input text is transmitted to OpenAI and is subject to [OpenAI's usage policies](https://openai.com/policies/usage-policies). We are not responsible for OpenAI's handling of data.

---

### 9. Disclaimers

THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE THAT:
- The Service will be uninterrupted or error-free
- Generated content will be accurate or suitable for your purposes
- The Service will meet your specific requirements

---

### 10. Limitation of Liability

To the maximum extent permitted by law, Replydesk AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service.

---

### 11. Changes to Terms

We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the updated Terms. We will update the "Last updated" date at the top of this page.

---

### 12. Governing Law

These Terms are governed by the laws of the jurisdiction in which Replydesk AI operates, without regard to conflict of law principles.

---

### 13. Contact

For questions about these Terms, contact us at:

**Email:** support@replydesk-ai.com
""")
